name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download DevTools
        run: wget https://github.com/pmmp/DevTools/releases/download/1.14.0/DevTools.phar -O ~/DevTools.phar
      - name: Build source code
        run: php -dphar.readonly=0 ~/DevTools.phar --make ./ --out ./out.phar
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: PHAR
          path: ./out.phar
